Repository PKNU-CERT-IS/BE, pull requests merged in 2025-08, with the labels that each got.

#10 Feat, Fix : auth 로직 구현 및 설정 오류 해결
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/workspace.xml
  src/main/java/org/certis/studyplatform/auth/application/object/command/GenerateTokenCommand.java
  src/main/java/org/certis/studyplatform/auth/application/object/command/LogoutCommand.java
  src/main/java/org/certis/studyplatform/auth/application/object/command/RefreshTokenCommand.java
  src/main/java/org/certis/studyplatform/auth/application/object/query/ValidateCredentialsQuery.java
  src/main/java/org/certis/studyplatform/auth/application/object/query/ValidateRefreshTokenQuery.java
  src/main/java/org/certis/studyplatform/auth/application/service/AuthCommandService.java
  src/main/java/org/certis/studyplatform/auth/application/service/AuthFacadeService.java
  src/main/java/org/certis/studyplatform/auth/application/service/AuthQueryService.java
  src/main/java/org/certis/studyplatform/auth/domain/model/vo/AccessTokenVo.java
  src/main/java/org/certis/studyplatform/auth/domain/model/vo/AccountNumberVo.java
  src/main/java/org/certis/studyplatform/auth/domain/model/vo/AuthInfoVo.java
  src/main/java/org/certis/studyplatform/auth/domain/model/vo/EncodedPasswordVo.java
  src/main/java/org/certis/studyplatform/auth/domain/model/vo/RawPasswordVo.java
  src/main/java/org/certis/studyplatform/auth/domain/model/vo/RefreshTokenVo.java
  src/main/java/org/certis/studyplatform/auth/domain/model/vo/TokenInfoVo.java
  src/main/java/org/certis/studyplatform/auth/domain/repository/AuthCommandRepository.java
  src/main/java/org/certis/studyplatform/auth/domain/repository/AuthQueryRepository.java
  src/main/java/org/certis/studyplatform/auth/domain/repository/RedisRefreshTokenRepository.java
  src/main/java/org/certis/studyplatform/auth/domain/service/AuthDomainService.java
  src/main/java/org/certis/studyplatform/auth/infrastructure/persistence/AuthCommandRepositoryImpl.java
  src/main/java/org/certis/studyplatform/auth/infrastructure/persistence/AuthEntity.java
  src/main/java/org/certis/studyplatform/auth/infrastructure/persistence/AuthJpaRepository.java
  src/main/java/org/certis/studyplatform/auth/infrastructure/persistence/AuthQueryRepositoryImpl.java
  src/main/java/org/certis/studyplatform/auth/infrastructure/persistence/RedisRefreshTokenRepositoryImpl.java
  src/main/java/org/certis/studyplatform/auth/presentation/AuthController.java
  src/main/java/org/certis/studyplatform/auth/presentation/dto/request/AuthMemberIdRequestDto.java
  src/main/java/org/certis/studyplatform/auth/presentation/dto/request/LoginRequestDto.java
  src/main/java/org/certis/studyplatform/auth/presentation/dto/response/LoginResponseDto.java
  src/main/java/org/certis/studyplatform/auth/presentation/dto/response/RefreshAccessTokenResponseDto.java
  src/main/java/org/certis/studyplatform/auth/presentation/dto/response/TokenRequestDto.java
  src/main/java/org/certis/studyplatform/exception/ExceptionStatus.java
  src/main/java/org/certis/studyplatform/member/application/MemberFacadeService.java
  src/main/java/org/certis/studyplatform/member/application/command/MemberCommandService.java
  src/main/java/org/certis/studyplatform/member/application/query/MemberQueryService.java
  src/main/java/org/certis/studyplatform/member/domain/Member.java
  src/main/java/org/certis/studyplatform/member/domain/MemberRole.java
  src/main/java/org/certis/studyplatform/member/domain/repository/MemberQueryRepository.java
  src/main/java/org/certis/studyplatform/member/domain/service/MemberDomainService.java
  src/main/java/org/certis/studyplatform/member/domain/vo/RoleVo.java
  src/main/java/org/certis/studyplatform/member/infrastructure/jpa/MemberJpaRepository.java
  src/main/java/org/certis/studyplatform/member/infrastructure/mapper/MemberMapper.java
  src/main/java/org/certis/studyplatform/member/infrastructure/persistence/MemberQueryRepositoryImpl.java
  src/main/java/org/certis/studyplatform/member/infrastructure/persistence/entity/MemberEntity.java
  src/main/java/org/certis/studyplatform/member/presentation/MemberController.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/request/CreateMemberRequestDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/request/MemberSearchRequestDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/MemberInfoResponseDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/MemberSearchResponseDto.java
  src/main/java/org/certis/studyplatform/shared/config/CorsConfig.java
  src/main/java/org/certis/studyplatform/shared/config/RedisConfig.java
  src/main/java/org/certis/studyplatform/shared/config/SecurityConfig.java
  src/main/java/org/certis/studyplatform/shared/security/JwtAuthenticationFilter.java
  src/main/java/org/certis/studyplatform/shared/security/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: bug, feat

#12 Feat,Refactor : 회원 가입 요청 및 로그인 disable 로직 구현
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/workspace.xml
  src/main/java/org/certis/studyplatform/auth/application/object/command/CreateAuthCommand.java
  src/main/java/org/certis/studyplatform/auth/application/service/AuthCommandService.java
  src/main/java/org/certis/studyplatform/auth/application/service/AuthFacadeService.java
  src/main/java/org/certis/studyplatform/auth/domain/model/vo/AuthCreationVo.java
  src/main/java/org/certis/studyplatform/auth/domain/model/vo/RawPasswordVo.java
  src/main/java/org/certis/studyplatform/auth/domain/repository/AuthCommandRepository.java
  src/main/java/org/certis/studyplatform/auth/domain/repository/AuthQueryRepository.java
  src/main/java/org/certis/studyplatform/auth/domain/service/AuthDomainService.java
  src/main/java/org/certis/studyplatform/auth/infrastructure/mapper/AuthCreationMapper.java
  src/main/java/org/certis/studyplatform/auth/infrastructure/persistence/AuthCommandRepositoryImpl.java
  src/main/java/org/certis/studyplatform/auth/infrastructure/persistence/AuthJpaRepository.java
  src/main/java/org/certis/studyplatform/auth/infrastructure/persistence/AuthQueryRepositoryImpl.java
  src/main/java/org/certis/studyplatform/auth/presentation/AuthController.java
  src/main/java/org/certis/studyplatform/auth/presentation/dto/request/RegisterRequestDto.java
  src/main/java/org/certis/studyplatform/exception/ExceptionStatus.java
  src/main/java/org/certis/studyplatform/member/application/command/MemberCommandService.java
  src/main/java/org/certis/studyplatform/member/application/mapper/MemberApplicationCommandMapper.java
  src/main/java/org/certis/studyplatform/member/application/mapper/MemberApplicationMapper.java
  src/main/java/org/certis/studyplatform/member/application/object/command/CreateMemberCommand.java
  src/main/java/org/certis/studyplatform/member/domain/MemberRole.java
  src/main/java/org/certis/studyplatform/member/domain/mapper/MemberDomainCommandMapper.java
  src/main/java/org/certis/studyplatform/member/domain/service/MemberDomainService.java
  src/main/java/org/certis/studyplatform/member/domain/vo/BirthdayVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/MemberCreationVo.java
  src/main/java/org/certis/studyplatform/member/infrastructure/mapper/MemberInfrastructureEntityMapper.java
  src/main/java/org/certis/studyplatform/member/infrastructure/mapper/MemberInfrastructureVoMapper.java
  src/main/java/org/certis/studyplatform/member/infrastructure/persistence/MemberCommandRepositoryImpl.java
  src/main/java/org/certis/studyplatform/member/presentation/MemberController.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/request/MemberCreateRequestDto.java
  src/main/java/org/certis/studyplatform/response/ResponseStatus.java
Labels: feat, refactor

#14 Feat: 어드민 회원 정보 수정 및 허가 로직 구현
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/org/certis/studyplatform/exception/ExceptionStatus.java
  src/main/java/org/certis/studyplatform/member/application/MemberFacadeService.java
  src/main/java/org/certis/studyplatform/member/application/command/MemberCommandService.java
  src/main/java/org/certis/studyplatform/member/application/object/command/UpdateMemberAdminFieldsCommand.java
  src/main/java/org/certis/studyplatform/member/domain/MemberRole.java
  src/main/java/org/certis/studyplatform/member/domain/service/MemberDomainService.java
  src/main/java/org/certis/studyplatform/member/domain/vo/AdminMemberUpdateResultVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/RoleVo.java
  src/main/java/org/certis/studyplatform/member/presentation/AdminMemberController.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/request/AdminMemberUpdateRequestDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/AdminMemberUpdateResponseDto.java
  src/main/java/org/certis/studyplatform/response/ResponseStatus.java
  src/main/java/org/certis/studyplatform/shared/security/JwtAuthenticationFilter.java
  src/main/resources/db/V2__Insert_member_data.sql
Labels: feat

#13 Member Profile API 및 로직 구현
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/workspace.xml
  src/main/java/org/certis/studyplatform/member/application/mapper/ProfileApplicationDtoMapper.java
  src/main/java/org/certis/studyplatform/member/domain/MemberGrade.java
  src/main/java/org/certis/studyplatform/member/domain/service/GracePeriodCalculationService.java
  src/main/java/org/certis/studyplatform/member/domain/service/ProfileDomainService.java
  src/main/java/org/certis/studyplatform/member/domain/vo/ProfileBlogVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/ProfileProjectVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/ProfileStudyVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/ProfileVo.java
  src/main/java/org/certis/studyplatform/member/infrastructure/mapper/MemberInfrastructureMapper.java
  src/main/java/org/certis/studyplatform/member/infrastructure/persistence/ProfileQueryRepositoryImpl.java
  src/main/java/org/certis/studyplatform/member/presentation/ProfileController.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/request/MemberFindOneRequestDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/ProfileBlogResponseDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/ProfileInfoResponseDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/ProfileProjectResponseDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/ProfileStudyResponseDto.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/ProjectEntity.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/ProjectStatus.java
  src/main/java/org/certis/studyplatform/shared/config/JacksonConfiguration.java
  src/main/java/org/certis/studyplatform/shared/security/CurrentUser.java
  src/main/java/org/certis/studyplatform/shared/util/DateTimeUtils.java
  src/main/java/org/certis/studyplatform/shared/util/GracePeriodCalculator.java
  src/main/java/org/certis/studyplatform/study/infrastructure/persistence/StudyEntity.java
  src/main/java/org/certis/studyplatform/study/infrastructure/persistence/StudyStatus.java
  src/main/resources/application-embedded.yml
  src/main/resources/application.yml
Labels: feat

#18 Schedule 도메인 구현
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/workspace.xml
  src/main/java/org/certis/studyplatform/auth/domain/service/AuthDomainService.java
  src/main/java/org/certis/studyplatform/auth/infrastructure/persistence/AuthJpaRepository.java
  src/main/java/org/certis/studyplatform/exception/ExceptionStatus.java
  src/main/java/org/certis/studyplatform/member/presentation/AdminMemberController.java
  src/main/java/org/certis/studyplatform/response/ResponseStatus.java
  src/main/java/org/certis/studyplatform/schedule/application/mapper/ScheduleApplicationMapper.java
  src/main/java/org/certis/studyplatform/schedule/application/object/command/ApproveOrRejectScheduleRequestCommand.java
  src/main/java/org/certis/studyplatform/schedule/application/object/command/CreateClubRoomUsageCommand.java
  src/main/java/org/certis/studyplatform/schedule/application/object/command/CreateScheduleByAdminCommand.java
  src/main/java/org/certis/studyplatform/schedule/application/object/command/DeleteClubRoomUsageCommand.java
  src/main/java/org/certis/studyplatform/schedule/application/object/command/DeleteScheduleCommand.java
  src/main/java/org/certis/studyplatform/schedule/application/object/query/GetAllApprovedScheduleRequestsQuery.java
  src/main/java/org/certis/studyplatform/schedule/application/object/query/GetMyRequestsQuery.java
  src/main/java/org/certis/studyplatform/schedule/application/object/query/GetPendingScheduleRequestsQuery.java
  src/main/java/org/certis/studyplatform/schedule/application/service/ScheduleCommandService.java
  src/main/java/org/certis/studyplatform/schedule/application/service/ScheduleFacadeService.java
  src/main/java/org/certis/studyplatform/schedule/application/service/ScheduleQueryService.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/ScheduleStatus.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/vo/AdminScheduleVo.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/vo/ScheduleDateTimeVo.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/vo/ScheduleDateVo.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/vo/ScheduleDescriptionVo.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/vo/ScheduleIdVo.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/vo/SchedulePlaceVo.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/vo/ScheduleStatusVo.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/vo/ScheduleTitleVo.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/vo/ScheduleTypeVo.java
  src/main/java/org/certis/studyplatform/schedule/domain/model/vo/ScheduleVo.java
  src/main/java/org/certis/studyplatform/schedule/domain/repository/ScheduleCommandRepository.java
  src/main/java/org/certis/studyplatform/schedule/domain/repository/ScheduleQueryRepository.java
  src/main/java/org/certis/studyplatform/schedule/domain/service/ScheduleDomainService.java
  src/main/java/org/certis/studyplatform/schedule/infrastructure/mapper/ScheduleInfrastructureMapper.java
  src/main/java/org/certis/studyplatform/schedule/infrastructure/persistence/ScheduleCommandRepositoryImpl.java
  src/main/java/org/certis/studyplatform/schedule/infrastructure/persistence/ScheduleJpaRepository.java
  src/main/java/org/certis/studyplatform/schedule/infrastructure/persistence/ScheduleQueryRepositoryImpl.java
  src/main/java/org/certis/studyplatform/schedule/infrastructure/persistence/ScheduleStatusJpaRepository.java
  src/main/java/org/certis/studyplatform/schedule/presentation/AdminScheduleController.java
  src/main/java/org/certis/studyplatform/schedule/presentation/ScheduleController.java
  src/main/java/org/certis/studyplatform/schedule/presentation/dto/request/AdminScheduleCreateRequestDto.java
  src/main/java/org/certis/studyplatform/schedule/presentation/dto/request/AdminScheduleDeleteRequestDto.java
  src/main/java/org/certis/studyplatform/schedule/presentation/dto/request/AdminScheduleUpdateRequestDto.java
  src/main/java/org/certis/studyplatform/schedule/presentation/dto/request/ClubRoomUsageDeleteRequestDto.java
  src/main/java/org/certis/studyplatform/schedule/presentation/dto/request/ClubRoomUsageRequestDto.java
  src/main/java/org/certis/studyplatform/schedule/presentation/dto/response/AdminScheduleResponseDto.java
  src/main/java/org/certis/studyplatform/schedule/presentation/dto/response/ScheduleResponseDto.java
  src/main/java/org/certis/studyplatform/shared/security/MockCurrentUserProvider.java
Labels: feat

#35 Refactor Entity and Trim white spaces
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/compiler.xml
  src/main/java/org/certis/generated/jooq/tables/records/ScheduleStatusRecord.java
  src/main/java/org/certis/studyplatform/member/application/mapper/MemberApplicationCommandMapper.java
  src/main/java/org/certis/studyplatform/member/application/mapper/MemberApplicationMapper.java
  src/main/java/org/certis/studyplatform/member/application/mapper/MemberApplicationQueryMapper.java
  src/main/java/org/certis/studyplatform/member/application/object/command/CreateMemberCommand.java
  src/main/java/org/certis/studyplatform/member/application/object/query/GetMemberByIdQuery.java
  src/main/java/org/certis/studyplatform/member/application/object/query/SearchMembersQuery.java
  src/main/java/org/certis/studyplatform/member/application/query/MemberQueryService.java
  src/main/java/org/certis/studyplatform/member/domain/Member.java
  src/main/java/org/certis/studyplatform/member/domain/MemberGrade.java
  src/main/java/org/certis/studyplatform/member/domain/Profile.java
  src/main/java/org/certis/studyplatform/member/domain/service/GracePeriodCalculationService.java
  src/main/java/org/certis/studyplatform/member/domain/service/MemberDomainService.java
  src/main/java/org/certis/studyplatform/member/domain/service/ProfileDomainService.java
  src/main/java/org/certis/studyplatform/member/domain/vo/BirthdayVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/EmailVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/GenderVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/GradeVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/MajorVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/MemberCreatedVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/MemberCreationVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/MemberFilterVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/MemberIdVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/MemberSummaryVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/MemberUpdateVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/MemberUpdatedVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/MemberVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/NameVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/ProfileBlogVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/ProfileProjectVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/ProfileStudyVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/ProfileUpdateVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/ProfileVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/RoleVo.java
  src/main/java/org/certis/studyplatform/member/domain/vo/StudentNumberVo.java
  src/main/java/org/certis/studyplatform/member/infrastructure/mapper/MemberInfrastructureEntityMapper.java
  src/main/java/org/certis/studyplatform/member/infrastructure/persistence/MemberCommandRepositoryImpl.java
  src/main/java/org/certis/studyplatform/member/infrastructure/persistence/ProfileQueryRepositoryImpl.java
  src/main/java/org/certis/studyplatform/member/infrastructure/persistence/entity/MemberPenaltyEntity.java
  src/main/java/org/certis/studyplatform/member/infrastructure/persistence/jpa/MemberJpaRepository.java
  src/main/java/org/certis/studyplatform/member/presentation/MemberController.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/request/MemberCreateRequestDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/request/MemberSearchRequestDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/request/MemberUpdateRequestDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/request/ProfileUpdateRequestDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/MemberInfoResponseDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/MemberResponseDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/MemberSearchResponseDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/ProfileBlogResponseDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/ProfileProjectResponseDto.java
  src/main/java/org/certis/studyplatform/member/presentation/dto/response/ProfileStudyResponseDto.java
  src/main/java/org/certis/studyplatform/shared/security/CurrentUser.java
  src/main/java/org/certis/studyplatform/shared/type/AttachedType.java
  src/main/java/org/certis/studyplatform/shared/util/DataConverter.java
  src/main/java/org/certis/studyplatform/shared/util/DateTimeUtils.java
  src/main/java/org/certis/studyplatform/shared/util/GracePeriodCalculator.java
Labels: feat, build, chore, fix

#43 Board Domain Basic Test Code
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/certIs.iml
  .idea/compiler.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  src/main/java/org/certis/studyplatform/board/domain/model/vo/BoardStatsVo.java
  src/main/java/org/certis/studyplatform/board/presentation/dto/request/AttachmentRequestDto.java
  src/main/java/org/certis/studyplatform/board/presentation/dto/request/BoardCreateRequestDto.java
  src/main/java/org/certis/studyplatform/board/presentation/dto/request/BoardUpdateRequestDto.java
  src/test/java/org/certis/studyplatform/board/domain/model/vo/AttachmentVoTest.java
  src/test/java/org/certis/studyplatform/board/domain/model/vo/BoardContentVoTest.java
  src/test/java/org/certis/studyplatform/board/domain/model/vo/BoardCreationVoTest.java
  src/test/java/org/certis/studyplatform/board/domain/model/vo/BoardDescriptionVoTest.java
  src/test/java/org/certis/studyplatform/board/domain/model/vo/BoardIdVoTest.java
  src/test/java/org/certis/studyplatform/board/domain/model/vo/BoardSearchVoTest.java
  src/test/java/org/certis/studyplatform/board/domain/model/vo/BoardStatsVoTest.java
  src/test/java/org/certis/studyplatform/board/domain/model/vo/BoardTitleVoTest.java
  src/test/java/org/certis/studyplatform/board/domain/model/vo/BoardVoTest.java
  src/test/java/org/certis/studyplatform/board/domain/service/BoardDomainServiceTest.java
  src/test/java/org/certis/studyplatform/board/presentation/BoardControllerTest.java
  src/test/resources/application-test.yml
Labels: test

#37 Project CRUD domain 구현
  src/main/java/org/certis/studyplatform/project/application/ProjectFacadeService.java
  src/main/java/org/certis/studyplatform/project/application/command/ProjectCommandService.java
  src/main/java/org/certis/studyplatform/project/application/mapper/ProjectApplicationCommandMapper.java
  src/main/java/org/certis/studyplatform/project/application/mapper/ProjectApplicationDtoMapper.java
  src/main/java/org/certis/studyplatform/project/application/mapper/ProjectApplicationQueryMapper.java
  src/main/java/org/certis/studyplatform/project/application/object/command/CreateProjectCommand.java
  src/main/java/org/certis/studyplatform/project/application/object/command/DeleteProjectCommand.java
  src/main/java/org/certis/studyplatform/project/application/object/query/GetAllProjectsQuery.java
  src/main/java/org/certis/studyplatform/project/application/object/query/GetProjectByIdQuery.java
  src/main/java/org/certis/studyplatform/project/application/object/query/SearchProjectsQuery.java
  src/main/java/org/certis/studyplatform/project/application/query/ProjectQueryService.java
  src/main/java/org/certis/studyplatform/project/domain/Project.java
  src/main/java/org/certis/studyplatform/project/domain/repository/ProjectCommandRepository.java
  src/main/java/org/certis/studyplatform/project/domain/repository/ProjectQueryRepository.java
  src/main/java/org/certis/studyplatform/project/domain/repository/ProjectRepository.java
  src/main/java/org/certis/studyplatform/project/domain/service/ProjectDomainService.java
  src/main/java/org/certis/studyplatform/project/domain/vo/MonthlyMeetingStatisticsVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectCreateVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectSearchCriteriaVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectSearchResultVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectStatus.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectSummaryVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectUpdateVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectVo.java
  src/main/java/org/certis/studyplatform/project/infrastructure/mapper/ProjectInfrastructureMapper.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/ProjectCommandRepositoryImpl.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/ProjectQueryRepositoryImpl.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/jpa/ProjectJpaRepository.java
  src/main/java/org/certis/studyplatform/project/presentation/ProjectController.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectAdvancedSearchRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectCreateRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectDeleteRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectDetailRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectSearchRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectUpdateRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/response/ProjectDetailResponseDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/response/ProjectSummaryResponseDto.java
Labels: feat

#38 Project participant domain 구현
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/workspace.xml
  src/main/java/org/certis/studyplatform/project/application/ProjectParticipantFacadeService.java
  src/main/java/org/certis/studyplatform/project/application/command/ProjectParticipantCommandService.java
  src/main/java/org/certis/studyplatform/project/application/object/command/CancelProjectParticipantCommand.java
  src/main/java/org/certis/studyplatform/project/application/object/command/CreateProjectParticipantCommand.java
  src/main/java/org/certis/studyplatform/project/application/object/command/UpdateProjectParticipantStatusCommand.java
  src/main/java/org/certis/studyplatform/project/application/query/ProjectParticipantQueryService.java
  src/main/java/org/certis/studyplatform/project/domain/ProjectParticipantStatus.java
  src/main/java/org/certis/studyplatform/project/domain/repository/ProjectParticipantCommandRepository.java
  src/main/java/org/certis/studyplatform/project/domain/repository/ProjectParticipantQueryRepository.java
  src/main/java/org/certis/studyplatform/project/domain/service/ProjectParticipantDomainService.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectParticipantCreatedVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectParticipantStatusUpdatedVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectParticipantSummaryVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectParticipantVo.java
  src/main/java/org/certis/studyplatform/project/infrastructure/mapper/ProjectAttachedInfrastructureMapper.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/ProjectParticipantCommandRepositoryImpl.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/ProjectParticipantQueryRepositoryImpl.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/jpa/ProjectParticipantJpaRepository.java
  src/main/java/org/certis/studyplatform/project/presentation/ProjectParticipantController.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectJoinApproveRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectJoinCancelRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectJoinRejectRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectJoinRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/response/ProjectJoinResponseDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/response/ProjectParticipantDetailResponseDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/response/ProjectParticipantStatsResponseDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/response/ProjectParticipantStatusUpdateResponseDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/response/ProjectParticipantSummaryResponseDto.java
Labels: feat

#39 Project Meeting domain 구현
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/org/certis/studyplatform/project/application/ProjectMeetingFacadeService.java
  src/main/java/org/certis/studyplatform/project/application/command/ProjectMeetingCommandService.java
  src/main/java/org/certis/studyplatform/project/application/object/command/CreateProjectAttachedCommand.java
  src/main/java/org/certis/studyplatform/project/application/object/command/CreateProjectMeetingCommand.java
  src/main/java/org/certis/studyplatform/project/application/object/command/DeleteProjectMeetingCommand.java
  src/main/java/org/certis/studyplatform/project/application/object/query/GetAllProjectMeetingsQuery.java
  src/main/java/org/certis/studyplatform/project/application/object/query/GetProjectMeetingByIdQuery.java
  src/main/java/org/certis/studyplatform/project/application/query/ProjectMeetingQueryService.java
  src/main/java/org/certis/studyplatform/project/domain/repository/ProjectMeetingCommandRepository.java
  src/main/java/org/certis/studyplatform/project/domain/repository/ProjectMeetingLinkCommandRepository.java
  src/main/java/org/certis/studyplatform/project/domain/repository/ProjectMeetingLinkQueryRepository.java
  src/main/java/org/certis/studyplatform/project/domain/repository/ProjectMeetingQueryRepository.java
  src/main/java/org/certis/studyplatform/project/domain/service/ProjectMeetingDomainService.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectAttachedVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectMeetingCreatedVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectMeetingDetailVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectMeetingLinkVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectMeetingPageResultVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectMeetingSearchCriteria.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectMeetingStatisticsVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectMeetingSummaryVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectMeetingSummaryWithLinksVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectMeetingUpdatedVo.java
  src/main/java/org/certis/studyplatform/project/domain/vo/ProjectMeetingVo.java
  src/main/java/org/certis/studyplatform/project/infrastructure/mapper/ProjectMeetingInfrastructureMapper.java
  src/main/java/org/certis/studyplatform/project/infrastructure/mapper/ProjectMeetingLinkInfrastructureMapper.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/ProjectMeetingCommandRepositoryImpl.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/ProjectMeetingLinkCommandRepositoryImpl.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/ProjectMeetingLinkQueryRepositoryImpl.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/ProjectMeetingQueryRepositoryImpl.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/jpa/ProjectAttachedJpaRepository.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/jpa/ProjectMeetingJpaRepository.java
  src/main/java/org/certis/studyplatform/project/infrastructure/persistence/jpa/ProjectMeetingLinkJpaRepository.java
  src/main/java/org/certis/studyplatform/project/presentation/ProjectMeetingController.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectAttachedCreateRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectMeetingAllRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectMeetingCreateRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectMeetingDeleteRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectMeetingDetailRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/request/ProjectMeetingUpdateRequestDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/response/ProjectAttachedResponseDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/response/ProjectMeetingDetailResponseDto.java
  src/main/java/org/certis/studyplatform/project/presentation/dto/response/ProjectMeetingSummaryResponseDto.java
Labels: feat
